# Generated by Django 4.0.2 on 2022-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_freak_bio_alter_freak_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freak',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
