# Generated by Django 4.0.2 on 2022-02-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_freak_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=1000)),
                ('freak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main_app.freak')),
            ],
        ),
    ]
