# Generated by Django 4.0.2 on 2022-02-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='https://static.wikia.nocookie.net/marveldatabase/images/9/99/Daily_Bugle_%28Earth-1048%29_from_Marvel%27s_Spider-Man_%28video_game%29_001.jpg/revision/latest?cb=20180930035134', max_length=500),
        ),
    ]
