# Generated by Django 4.0.2 on 2022-02-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=500)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['headline']},
        ),
    ]
